using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Enemy : MonoBehaviour
{

    public float speed;
    public Rigidbody2D target;

    bool isLive = true;

    Rigidbody2D rigid;
    SpriteRenderer spriter; 

    private void Awake()
    {
        rigid = GetComponent<Rigidbody2D>();
        spriter = GetComponent<SpriteRenderer>();
    }

    private void FixedUpdate()
    {

        if (!isLive)
            return;


        // ภงฤก ย๗ภฬ = ลธฐู ภงฤก - ณชภว ภงฤก
        Vector2 dirVec = target.position - rigid.position;
        Vector2 nextVec = dirVec.normalized * speed * Time.fixedDeltaTime;
        rigid.MovePosition(rigid.position + nextVec);
        rigid.velocity = Vector2.zero;  // วรทนภฬพ๎ฟอ บฮต๚รฤตต ภฬตฟวฯม๖ พสตตทฯ
        // นๆวโ = ภงฤก ย๗ภฬภว มคฑิศญ (Normalized)
        // nextVec : วรทนภฬพ๎ภว ลฐภิทย ฐชภป ด๕วั ภฬตฟ = ธ๓ฝบลอภว นๆวโ ฐชภป ด๕วั ภฬตฟ
    }


    private void LateUpdate()
    {
        if (!isLive)
            return;

        spriter.flipX = target.position.x < rigid.position.x;
    }
}
